name: suuqa
description: A Better E-Commerce
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  suuqa_common:
    path: ../suuqa_common

  camera:
  country_pickers:
  cupertino_icons:
  device_info:
  bloc:
  flutter_bloc:
  flushbar:
  flutter_auth_buttons:
  flutter_masked_text:
  google_places_picker:
  image_picker:
  intl:
  page_transition:
  page_view_indicator:
  path_provider:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/images/gradient.png
    - lib/src/assets/images/placeholder-profile.png
    - lib/src/assets/images/upload-photo.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700